### ISSUE TITLE
Air Pricing Modifiers

### ISSUE THREAD

**Issue by nitincdac** [Travelport/travelport-uapi-tutorial-php#83]
Hi

Below is my resuest message : 

```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
	<soapenv:Header/>
	<soapenv:Body>
		<air:LowFareSearchReq
			xmlns:air="http://www.travelport.com/schema/air_v42_0" TraceId="trace" AuthorizedBy="user" TargetBranch="P108164" SolutionResult="true">
			<com:BillingPointOfSaleInfo
				xmlns:com="http://www.travelport.com/schema/common_v42_0" OriginApplication="UAPI">
			</com:BillingPointOfSaleInfo>
			<air:SearchAirLeg>
				<air:SearchOrigin>
					<com:Airport
						xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="DEL">
					</com:Airport>
				</air:SearchOrigin>
				<air:SearchDestination>
					<com:Airport
						xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="YYZ">
					</com:Airport>
				</air:SearchDestination>
				<air:SearchDepTime PreferredTime="2017-10-07"/>
			</air:SearchAirLeg>
			<air:AirSearchModifiers>
				<air:PreferredProviders>
					<com:Provider
						xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="1P">
					</com:Provider>
				</air:PreferredProviders>
				<air:PermittedCarriers>
					<com:Carrier
						xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="AF">
					</com:Carrier>
				</air:PermittedCarriers>
				<air:PermittedCabins>
					<com:CabinClass
						xmlns:com="http://www.travelport.com/schema/common_v42_0" Type="Economy">
					</com:CabinClass>
				</air:PermittedCabins>
			</air:AirSearchModifiers>
			<com:SearchPassenger
				xmlns:com="http://www.travelport.com/schema/common_v42_0" BookingTravelerRef="0" Code="ADT">
			</com:SearchPassenger>
		</air:LowFareSearchReq>
	</soapenv:Body>
</soapenv:Envelope>
```

I want to add Air Pricing Modifiers like 'Booking Code' , 'Fare Type' & 'Alternate Currencies' to this request. Please guide me how would I do that ?

regards

**Comment by vivekjyotipramanik** [comment]
Hi nitincdac,

Please find below the request xml with all the details added. There are few different kinds of Fares that can be used in the request. Please find below the link with all the different fareTypes and their details. Please let us know how it goes. Thanks.

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <air:LowFareSearchReq TargetBranch="TRGT_BRCH" TraceId="Trace" SolutionResult="true" AuthorizedBy="USER" xmlns:air="http://www.travelport.com/schema/air_v41_0" xmlns:com="http://www.travelport.com/schema/common_v41_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:CityOrAirport Code="DEN"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:CityOrAirport Code="ATL"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2017-08-26"/>
            <air:AirLegModifiers>
               <air:PermittedBookingCodes>
                  <air:BookingCode Code="Y"/>
               </air:PermittedBookingCodes>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:CityOrAirport Code="ATL"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:CityOrAirport Code="DEN"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2017-09-05"/>
            <air:AirLegModifiers>
               <air:PermittedBookingCodes>
                  <air:BookingCode Code="Y"/>
               </air:PermittedBookingCodes>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:AirSearchModifiers IncludeFlightDetails="true">
            <air:PreferredProviders>
               <com:Provider Code="1V"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
         <com:SearchPassenger Code="ADT"/>
         <air:AirPricingModifiers CurrencyType="GBP" FaresIndicator="AllFares"/>
      </air:LowFareSearchReq>
   </soap:Body>
</soap:Envelope>
```


https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_by_Fare_Type.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CLow%2520Fare%2520Shopping%7CLow%2520Fare%2520Shopping%2520Pricing%2520Modifiers%7C_____3

**Comment by nitincdac** [comment]
Hi vivekjyotipramanik

thanks for your message, I am working on thie & will update you for the same. 

I am using the followinf documentation : [](https://support.travelport.com/webhelp/uapi/uAPI.htm)

Does all of these examples are mentioned in the  documnetation as well ? because I have tried to find it, but couldn't find it. e.g. like if I have to add "FaresIndicator" in the request, this should be the line of code "<air:AirPricingModifiers FaresIndicator="AllFares"/>"  etc. 

regards

**Comment by vivekjyotipramanik** [comment]
Hi nitincdac,

Please find below the details regarding your questions. Please let us know how it goes. Thanks.



 1.   Does all of these examples are mentioned in the documnetation as well ? because I have tried to find it, but couldn't find it. e.g. like if I have to add "FaresIndicator" in the request, this should be the line of code "<air:AirPricingModifiers FaresIndicator="AllFares"/>" etc.

There might not be all the examples available in Documentation, but in the request XML I sent yesterday consists of the FaresIndicator attribute. So, you can change the attribute value like AllFares, NetfaresOnly and you should receive the data properly.

2.    what is the difference between "Low Fare Shopping Search Modifiers" & "Low Fare Shopping Pricing Modifiers" ? If I am not wrong, as per the documentation "Booking Code" can be used in both. So what is the difference ?

AirSearchModifiers contains flight-related criteria that can be used to narrow a search response, such as preferred carriers and connecting cities, flight types, ticket types, and flexible dates, times, and airports. 

AirPricingModifiers contains fare-related criteria that can be used to narrow a search response, such as passenger type, cabin class, loyalty programs, and fare types. It also contains pricing-related criteria, such as fare restrictions, booking codes, permitted cabins, and negotiated rates.

 3.   What is the difference between "Booking Code" & "Cabin Class" ? Because in this example "#26" , it says that "ClassOfService" & "bookingcode " both are same.

BookignCode and ClassOfService are same. But BookingCode and cabinclass is different. 
BookingCode/ClassOfService is generally a one or 2 character letter which defines the Service class like Y, B, M, Q etc.

While  CabinClass is the class of the Cabin, like Economy, First, Business, PremiumEconomy etc.

4.    I have tried to add "FaresIndicator" in the "Air Pricing Modifiers" as you have explained in the above example as
    <air:AirPricingModifiers CurrencyType="GBP" FaresIndicator="AllFares"/>
    <air:AirPricingModifiers CurrencyType="GBP" FaresIndicator="NetFaresOnly"/>
    <air:AirPricingModifiers CurrencyType="GBP" FaresIndicator="PrivateFaresOnly"/>
    but only "AllFares" is working. All of the others are giving errors.

I believe you need to be provisioned properly to use the others. If you are using trial credentials, you would be able to use only AllFares, but if you are using PreProduction credentials, Please raise an ORS ticket/Right Now/MyTravelport ticket and an API Analyst will check the issue and assist you to set it up if needed.



Please find below the link with all the details about LowfareSearch.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_(Synchronous).htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CLow%2520Fare%2520Shopping%7C_____2

**Comment by nitincdac** [comment]
Hi vivekjyotipramanik

that is amazing explanation. thanks for your help

regards
